# Generated by Django 4.2 on 2023-04-21 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=36, verbose_name='部门名称')),
                ('create_time', models.DateTimeField(auto_now_add=True, max_length=10, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, max_length=10, verbose_name='修改时间')),
            ],
        ),
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personnel_name', models.CharField(max_length=36, verbose_name='员工姓名')),
                ('gender', models.SmallIntegerField(choices=[(1, '男'), (2, '女')], verbose_name='性别')),
                ('age', models.IntegerField(max_length=3, verbose_name='年龄')),
                ('salary', models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='薪资')),
                ('create_time', models.DateTimeField(auto_now_add=True, max_length=10, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, max_length=10, verbose_name='修改时间')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.department', verbose_name='部门ID')),
            ],
        ),
    ]
