# Generated by Django 4.2 on 2023-04-21 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='create_time',
            field=models.CharField(max_length=10, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='department',
            name='update_time',
            field=models.CharField(default='', max_length=10, verbose_name='修改时间'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='create_time',
            field=models.CharField(max_length=10, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='gender',
            field=models.SmallIntegerField(choices=[(2, '女'), (1, '男')], verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='update_time',
            field=models.CharField(max_length=10, verbose_name='修改时间'),
        ),
    ]
