# Generated by Django 4.2 on 2023-04-21 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_alter_department_create_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnel',
            name='age',
            field=models.IntegerField(verbose_name='年龄'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='gender',
            field=models.SmallIntegerField(choices=[(2, '女'), (1, '男')], verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='薪资'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='update_time',
            field=models.CharField(default='', max_length=19, verbose_name='修改时间'),
        ),
    ]
