# Generated by Django 4.2 on 2023-04-24 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_alter_personnel_age_alter_personnel_gender_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pretty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=11, verbose_name='手机号')),
                ('price', models.IntegerField(verbose_name='价格')),
                ('level', models.SmallIntegerField(default=1, verbose_name='级别')),
                ('state', models.SmallIntegerField(default=1, verbose_name='状态')),
                ('create_time', models.CharField(max_length=19, verbose_name='创建时间')),
                ('update_time', models.CharField(default='', max_length=19, verbose_name='修改时间')),
            ],
        ),
    ]
