# Generated by Django 4.2 on 2023-04-24 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_pretty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnel',
            name='update_time',
            field=models.CharField(blank=True, max_length=19, null=True, verbose_name='修改时间'),
        ),
        migrations.AlterField(
            model_name='pretty',
            name='update_time',
            field=models.CharField(blank=True, max_length=19, null=True, verbose_name='修改时间'),
        ),
    ]
