# Generated by Django 4.2 on 2023-04-24 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0006_alter_personnel_update_time_alter_pretty_update_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='update_time',
            field=models.CharField(blank=True, default='', max_length=19, null=True, verbose_name='修改时间'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='gender',
            field=models.SmallIntegerField(choices=[(1, '男'), (2, '女')], verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='update_time',
            field=models.CharField(blank=True, default='', max_length=19, null=True, verbose_name='修改时间'),
        ),
        migrations.AlterField(
            model_name='pretty',
            name='level',
            field=models.SmallIntegerField(choices=[(2, '2级'), (4, '4级'), (1, '1级'), (3, '3级')], default=1, verbose_name='级别'),
        ),
        migrations.AlterField(
            model_name='pretty',
            name='state',
            field=models.SmallIntegerField(choices=[(2, '已使用'), (1, '未使用')], default=1, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='pretty',
            name='update_time',
            field=models.CharField(blank=True, default='', max_length=19, null=True, verbose_name='修改时间'),
        ),
    ]
