# Generated by Django 4.2 on 2023-04-27 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0008_personnel_account_personnel_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Admin_name', models.CharField(max_length=36, verbose_name='管理员名称')),
                ('account', models.CharField(max_length=36, verbose_name='登录账号')),
                ('password', models.CharField(max_length=36, verbose_name='登录密码')),
                ('create_time', models.CharField(max_length=19, verbose_name='创建时间')),
                ('update_time', models.CharField(blank=True, default='', max_length=19, null=True, verbose_name='修改时间')),
            ],
        ),
        migrations.AlterField(
            model_name='personnel',
            name='account',
            field=models.CharField(max_length=36, verbose_name='登录账号'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='password',
            field=models.CharField(max_length=36, verbose_name='登录密码'),
        ),
        migrations.AlterField(
            model_name='pretty',
            name='level',
            field=models.SmallIntegerField(choices=[(4, '4级'), (1, '1级'), (3, '3级'), (2, '2级')], default=1, verbose_name='级别'),
        ),
    ]
