# Generated by Django 4.2 on 2023-04-27 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0009_admin_alter_personnel_account_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin',
            old_name='Admin_name',
            new_name='admin_name',
        ),
        migrations.AlterField(
            model_name='pretty',
            name='level',
            field=models.SmallIntegerField(choices=[(4, '4级'), (1, '1级'), (2, '2级'), (3, '3级')], default=1, verbose_name='级别'),
        ),
    ]
