# Generated by Django 4.2.1 on 2023-05-07 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0010_rename_admin_name_admin_admin_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pretty',
            name='level',
            field=models.SmallIntegerField(choices=[(4, '4级'), (3, '3级'), (1, '1级'), (2, '2级')], default=1, verbose_name='级别'),
        ),
    ]
