# Generated by Django 4.2.1 on 2023-05-07 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0012_alter_pretty_level_alter_pretty_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pretty',
            name='level',
            field=models.SmallIntegerField(choices=[(4, '4级'), (2, '2级'), (3, '3级'), (1, '1级')], default=1, verbose_name='级别'),
        ),
    ]
