# Generated by Django 4.2 on 2023-05-10 02:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0013_alter_pretty_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnel',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app01.department'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='薪资'),
        ),
        migrations.AlterField(
            model_name='pretty',
            name='level',
            field=models.SmallIntegerField(choices=[(3, '3级'), (1, '1级'), (4, '4级'), (2, '2级')], default=1, verbose_name='级别'),
        ),
        migrations.CreateModel(
            name='TaskManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.SmallIntegerField(choices=[(3, '临时'), (2, '一般'), (1, '重要')], default=3, verbose_name='级别')),
                ('task_title', models.CharField(max_length=36, verbose_name='任务标题')),
                ('task_details', models.TextField(verbose_name='任务详情')),
                ('create_time', models.CharField(max_length=19, verbose_name='创建时间')),
                ('update_time', models.CharField(blank=True, default='', max_length=19, null=True, verbose_name='修改时间')),
                ('task_head', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app01.admin', verbose_name='任务负责人')),
            ],
        ),
    ]
