# Generated by Django 4.2 on 2023-05-10 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0014_alter_personnel_department_alter_personnel_salary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnel',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.department', verbose_name='部门ID'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='gender',
            field=models.SmallIntegerField(choices=[(2, '女'), (1, '男')], verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='pretty',
            name='level',
            field=models.SmallIntegerField(choices=[(3, '3级'), (4, '4级'), (1, '1级'), (2, '2级')], default=1, verbose_name='级别'),
        ),
        migrations.AlterField(
            model_name='taskmanager',
            name='level',
            field=models.SmallIntegerField(choices=[(2, '一般'), (1, '重要'), (3, '临时')], default=3, verbose_name='级别'),
        ),
        migrations.AlterField(
            model_name='taskmanager',
            name='task_head',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.admin', verbose_name='任务负责人'),
        ),
    ]
