# Generated by Django 4.2 on 2023-05-12 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0015_alter_personnel_department_alter_personnel_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pretty',
            name='level',
            field=models.SmallIntegerField(choices=[(4, '4级'), (1, '1级'), (2, '2级'), (3, '3级')], default=1, verbose_name='级别'),
        ),
        migrations.AlterField(
            model_name='taskmanager',
            name='level',
            field=models.SmallIntegerField(choices=[(1, '重要'), (2, '一般'), (3, '临时')], default=3, verbose_name='级别'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=64, verbose_name='订单号')),
                ('trade_name', models.CharField(max_length=32, verbose_name='商品名称')),
                ('trade_price', models.IntegerField(verbose_name='商品价格')),
                ('trade_status', models.SmallIntegerField(choices=[(1, '待支付'), (2, '已支付')], default=1, verbose_name='商品状态')),
                ('trade_admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.admin', verbose_name='管理员')),
            ],
        ),
    ]
