# Generated by Django 4.2 on 2023-05-12 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0016_alter_pretty_level_alter_taskmanager_level_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='create_time',
            field=models.CharField(default=1, max_length=19, verbose_name='创建时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='update_time',
            field=models.CharField(blank=True, default='', max_length=19, null=True, verbose_name='修改时间'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='gender',
            field=models.SmallIntegerField(choices=[(1, '男'), (2, '女')], verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='pretty',
            name='level',
            field=models.SmallIntegerField(choices=[(3, '3级'), (1, '1级'), (4, '4级'), (2, '2级')], default=1, verbose_name='级别'),
        ),
        migrations.AlterField(
            model_name='pretty',
            name='state',
            field=models.SmallIntegerField(choices=[(2, '已使用'), (1, '未使用')], default=1, verbose_name='状态'),
        ),
    ]
