# Generated by Django 4.2 on 2023-05-18 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0018_alter_pretty_level_alter_pretty_state_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form_Uploads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='姓名')),
                ('age', models.IntegerField(verbose_name='年龄')),
                ('head_sculpture', models.FilePathField(max_length=255, verbose_name='头像')),
                ('create_time', models.CharField(max_length=19, verbose_name='创建时间')),
                ('update_time', models.CharField(blank=True, default='', max_length=19, null=True, verbose_name='修改时间')),
            ],
        ),
        migrations.AlterField(
            model_name='pretty',
            name='level',
            field=models.SmallIntegerField(choices=[(2, '2级'), (3, '3级'), (4, '4级'), (1, '1级')], default=1, verbose_name='级别'),
        ),
        migrations.AlterField(
            model_name='taskmanager',
            name='level',
            field=models.SmallIntegerField(choices=[(1, '重要'), (2, '一般'), (3, '临时')], default=3, verbose_name='级别'),
        ),
    ]
