# Generated by Django 4.2 on 2023-05-18 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0019_form_uploads_alter_pretty_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form_uploads',
            name='head_sculpture',
            field=models.CharField(max_length=255, verbose_name='头像'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='gender',
            field=models.SmallIntegerField(choices=[(2, '女'), (1, '男')], verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='pretty',
            name='level',
            field=models.SmallIntegerField(choices=[(2, '2级'), (3, '3级'), (1, '1级'), (4, '4级')], default=1, verbose_name='级别'),
        ),
        migrations.AlterField(
            model_name='pretty',
            name='state',
            field=models.SmallIntegerField(choices=[(2, '已使用'), (1, '未使用')], default=1, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='taskmanager',
            name='level',
            field=models.SmallIntegerField(choices=[(2, '一般'), (1, '重要'), (3, '临时')], default=3, verbose_name='级别'),
        ),
    ]
