# Generated by Django 4.2 on 2023-05-19 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0020_alter_form_uploads_head_sculpture_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelForm_Uploads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=64, verbose_name='城市名称')),
                ('city_population', models.IntegerField(verbose_name='城市人口')),
                ('city_logo', models.FileField(max_length=255, upload_to='', verbose_name='LOGO')),
                ('create_time', models.CharField(max_length=19, verbose_name='创建时间')),
                ('update_time', models.CharField(blank=True, default='', max_length=19, null=True, verbose_name='修改时间')),
            ],
        ),
        migrations.AlterField(
            model_name='pretty',
            name='level',
            field=models.SmallIntegerField(choices=[(1, '1级'), (2, '2级'), (3, '3级'), (4, '4级')], default=1, verbose_name='级别'),
        ),
        migrations.AlterField(
            model_name='taskmanager',
            name='level',
            field=models.SmallIntegerField(choices=[(3, '临时'), (1, '重要'), (2, '一般')], default=3, verbose_name='级别'),
        ),
    ]
